[package]
name = "vfio-ioctls"
version = "0.1.0"
authors = ["The Cloud Hypervisor Authors", "Liu Jiang <gerry@linux.alibaba.com>"]
description = "Safe wrappers over VFIO ioctls"
keywords = ["vfio"]
license = "Apache-2.0 OR BSD-3-Clause"
edition = "2018"

[dependencies]
byteorder = "~1.4.2"
log = "0.4"
kvm-bindings = "~0"
kvm-ioctls = "~0"
vfio-bindings = "~0"
vm-memory = { version = "~0", features = ["backend-mmap"] }
vmm-sys-util = "~0"
